## Data Preprocessing dengan Scikit Learn

### Sample Data
- pertama kita harus import numpy sbg np dan import preprocessing
- cara mengecek jumllah baris dan kolom bisa memasukkan .shape

In [4]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1, -1.9, 5.5],
                        [-1.5, 2.4, 3.5],
                        [0.5, -7.9, 5.6],
                        [5.9, 2.3, -5.8]])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [2]:
sample_data.shape

(4, 3)

### Binarisation 
- memanggil sample data yang sudah di buat sebelumnya

In [3]:
preprocessing = preprocessing.Binarizer(threshold=0.5)
binarised_data = preprocessing.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

### Scaling
- memanggil sample data yang sudah dibuat sebelumnya

In [5]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [6]:
preprocessing = preprocessing.MinMaxScaler(feature_range=(0, 1))
preprocessing.fit(sample_data)
scaled_data = preprocessing.transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

In [7]:
scaled_data = preprocessing.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

### L1 Normalisation: Least Absolute Deviations

- memanggil sample data yang sudah dibuat sebelumnya

In [8]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [21]:
l1_normalised_data = preprocessing.normalizer(sample_data, norm='l1')
l1_normalised_data

AttributeError: 'Binarizer' object has no attribute 'normalizer'

### L2 Normalisation: Least Squares

- Memanggil sample data yang sudah dibuat sebelumnya

In [22]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [25]:
l2_normalised_data = preprocessing.normalize(sample_data, norm='l2')
l2_normalised_data

AttributeError: 'Binarizer' object has no attribute 'normalize'